# coding: utf-8

"""
    Data Space Catalog Service

    The service provides a REST API for managing and sharing catalog items.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.api.mmio_api import MMIOApi


class TestMMIOApi(unittest.TestCase):
    """MMIOApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MMIOApi()

    def tearDown(self) -> None:
        pass

    def test_delete_mmio_file(self) -> None:
        """Test case for delete_mmio_file

        Delete Mmio File
        """
        pass

    def test_get_mmio_file(self) -> None:
        """Test case for get_mmio_file

        Get Mmio File
        """
        pass

    def test_save_mmio_file(self) -> None:
        """Test case for save_mmio_file

        Save Mmio File
        """
        pass


if __name__ == '__main__':
    unittest.main()
