# coding: utf-8

"""
    Data Space Catalog

    The service provides a REST API for managing and sharing catalog data. Interacts with connector services to obtain information about data products.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.models.catalog_item_form import CatalogItemForm

class TestCatalogItemForm(unittest.TestCase):
    """CatalogItemForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogItemForm:
        """Test CatalogItemForm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogItemForm`
        """
        model = CatalogItemForm()
        if include_optional:
            return CatalogItemForm(
                ontology = 'DCAT-3',
                title = '',
                summary = '',
                data_products = [
                    ds_catalog.models.data_product_form.DataProductForm(
                        id = '', 
                        name = '', 
                        size = null, 
                        mimetype = '', 
                        digest = '', 
                        source = ds_catalog.models.source.Source(
                            connector = ds_catalog.models.connector.Connector(
                                id = '', ), 
                            node = null, 
                            interface = null, ), 
                        access_point_url = '', )
                    ]
            )
        else:
            return CatalogItemForm(
                ontology = 'DCAT-3',
                title = '',
                summary = '',
                data_products = [
                    ds_catalog.models.data_product_form.DataProductForm(
                        id = '', 
                        name = '', 
                        size = null, 
                        mimetype = '', 
                        digest = '', 
                        source = ds_catalog.models.source.Source(
                            connector = ds_catalog.models.connector.Connector(
                                id = '', ), 
                            node = null, 
                            interface = null, ), 
                        access_point_url = '', )
                    ],
        )
        """

    def testCatalogItemForm(self):
        """Test CatalogItemForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
