# coding: utf-8

"""
    Data Space Catalog

    The service provides a REST API for managing and sharing catalog data. Interacts with connector services to obtain information about data products.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.api.catalog_items_data_api import CatalogItemsDataApi


class TestCatalogItemsDataApi(unittest.TestCase):
    """CatalogItemsDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogItemsDataApi()

    def tearDown(self) -> None:
        pass

    def test_change_catalog_item_data(self) -> None:
        """Test case for change_catalog_item_data

        Change the data for the catalog item
        """
        pass

    def test_create_catalog_item_data(self) -> None:
        """Test case for create_catalog_item_data

        Create the data for the catalog item
        """
        pass

    def test_delete_catalog_item_data(self) -> None:
        """Test case for delete_catalog_item_data

        Delete the data for the catalog item
        """
        pass

    def test_get_catalog_item_data(self) -> None:
        """Test case for get_catalog_item_data

        Get the data for the catalog item
        """
        pass


if __name__ == '__main__':
    unittest.main()
