# coding: utf-8

"""
    Data Space Catalog

    The service provides a REST API for managing and sharing catalog data. Interacts with connector services to obtain information about data products.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.api.sharing_api import SharingApi


class TestSharingApi(unittest.TestCase):
    """SharingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SharingApi()

    def tearDown(self) -> None:
        pass

    def test_share_dataset(self) -> None:
        """Test case for share_dataset

        Share Dataset
        """
        pass


if __name__ == '__main__':
    unittest.main()
