# coding: utf-8

"""
    Data Space Catalog

    The service provides a REST API for managing and sharing catalog data. Interacts with connector services to obtain information about data products.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.api.catalog_items_sharing_api import CatalogItemsSharingApi


class TestCatalogItemsSharingApi(unittest.TestCase):
    """CatalogItemsSharingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogItemsSharingApi()

    def tearDown(self) -> None:
        pass

    def test_share_catalog_item(self) -> None:
        """Test case for share_catalog_item

        Share a catalog item
        """
        pass


if __name__ == '__main__':
    unittest.main()
