# coding: utf-8

"""
    Data Space Catalog Service

    The service provides a REST API for managing and sharing catalog items.

    The version of the OpenAPI document: 0.1.1
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_catalog.api.catalog_api import CatalogApi


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogApi()

    def tearDown(self) -> None:
        pass

    def test_get_catalog(self) -> None:
        """Test case for get_catalog

        Get Local Catalog
        """
        pass


if __name__ == '__main__':
    unittest.main()
