{{- if and .Values.migrate.enabled (eq .Values.deploymentMode "daemonset") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-migrate-db
  labels:
    app: migrate-db
spec:
  selector:
    matchLabels:
      app: migrate-db
  template:
    metadata:
      labels:
        app: migrate-db
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: ds-neo4j-semantics-database
                topologyKey: kubernetes.io/hostname
                
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "poetry run python -m app.migrate_db"]
          env:
            - name: NEO4J_HOST
              value: "127.0.0.1"
            - name: NEO4J_BOLT_PORT
              value: "7687"
{{- end }}