services:
  neo4j:
    image: neo4j:5.23.0
    volumes:
      - ./volumes/neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env

  catalog:
    build: .
    ports:
      - "8001:80"
