"""Initial migration

Revision ID: 003ca28b0d70
Revises:
Create Date: 2024-09-11 10:32:56.143207

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "003ca28b0d70"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
