"""empty message

Revision ID: 09f035bb1d25
Revises: 003ca28b0d70
Create Date: 2024-09-11 14:53:10.887686

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09f035bb1d25"
down_revision: Union[str, None] = "003ca28b0d70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_local", sa.Boolean(), nullable=True),
        sa.Column("is_shared", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_items_created"), "catalog_items", ["created"], unique=False
    )
    op.create_index(op.f("ix_catalog_items_id"), "catalog_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_catalog_items_is_local"), "catalog_items", ["is_local"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_is_shared"), "catalog_items", ["is_shared"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_catalog_items_is_shared"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_is_local"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_created"), table_name="catalog_items")
    op.drop_table("catalog_items")
    # ### end Alembic commands ###
