replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /health-check/
    port: http
readinessProbe:
  httpGet:
    path: /health-check/
    port: http

catalog:
  title: Catalog
  description: My Local Catalog

neo4j:
  enabled: true
  neo4j:
    name: neo4j
    resources:
      cpu: "0.5"
      memory: "2Gi"
    passwordFromSecret: "neo4j-secrets"
  volumes:
    data:
      mode: defaultStorageClass
      defaultStorageClass:
        requests:
          storage: 2Gi
