replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: ""
nameOverride: ""
fullnameOverride: "ds-catalog"


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

container:
  command: ["uvicorn"]
  args: ["app.main:app", "--host", "0.0.0.0", "--port", "8081"]

service:
  type: ClusterIP
  port: 8081

livenessProbe:
  httpGet:
    path: /health-check/
    port: 8081

readinessProbe:
  httpGet:
    path: /health-check/
    port: 8081

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: ""
  mountPath: /code/uploads

catalog:
  title: Catalog
  description: My Local Catalog

database:
  protocol: bolt
  host: "127.0.0.1"
  port: 7687
  name: neo4j
  username: neo4j
  password: "123456789"  # Must match Neo4j's password

migrate:
  enabled: false

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

namespace: nextgen

deploymentMode: daemonset  # or "deployment"

ingress:
  host: nextgen.hiro-develop.nl
  nodes:
    - nodeId: hus
    - nodeId: ki
    - nodeId: uva
