openapi: 3.1.0
info:
  title: Data Space Catalog
  description: The service provides a REST API for managing and sharing catalog data.
    Interacts with connector services to obtain information about data products.
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/ds-catalog/blob/main/LICENSE
  version: 0.1.1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health-check/:
    get:
      summary: Health check
      description: Returns a 200 status code if the service is up and running
      operationId: health_check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /datasets/:
    get:
      tags:
      - Datasets
      summary: Get Datasets
      description: Get the datasets list
      operationId: get_datasets
      parameters:
      - name: page
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
            minimum: 1
          - type: 'null'
          title: Page
      - name: pageSize
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
            maximum: 100
            minimum: 1
          - type: 'null'
          title: Pagesize
      - name: orderBy
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Orderby
      - name: orderDirection
        in: query
        required: false
        schema:
          anyOf:
          - $ref: '#/components/schemas/OrderDirection'
          - type: 'null'
          title: Orderdirection
      - name: search
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Search
      - name: theme
        in: query
        required: false
        schema:
          anyOf:
          - type: array
            items:
              type: string
          - type: 'null'
          title: Theme
      - name: isLocal
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Islocal
      - name: isShared
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Isshared
      - name: creator__id
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Creator  Id
      - name: issued
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Issued
      - name: issued__gte
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Issued  Gte
      - name: issued__lte
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Issued  Lte
      - name: distribution__byteSize__gte
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
            minimum: 0
          - type: 'null'
          title: Distribution  Bytesize  Gte
      - name: distribution__byteSize__lte
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
            minimum: 0
          - type: 'null'
          title: Distribution  Bytesize  Lte
      - name: distribution__mimeType
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Distribution  Mimetype
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResult_Dataset_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - Datasets
      summary: Create Dataset
      description: Create a dataset
      operationId: create_dataset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetForm'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          headers:
            Location:
              description: The URL of the newly created resource
              schema:
                type: string
                format: uri
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /datasets/{id}/:
    get:
      tags:
      - Datasets
      summary: Get Dataset
      description: Get the dataset
      operationId: get_dataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        '404':
          description: Dataset not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - Datasets
      summary: Update Dataset
      description: Update the dataset
      operationId: update_dataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetForm'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        '404':
          description: Dataset not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - Datasets
      summary: Delete Dataset
      description: Delete the dataset
      operationId: delete_dataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '204':
          description: Successful Response
        '404':
          description: Dataset not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /datasets/{id}/share/:
    post:
      tags:
      - Sharing
      summary: Share Dataset
      description: Share the dataset to the marketplace
      operationId: share_dataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetShareForm'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          headers:
            Location:
              description: The URL of the newly created resource
              schema:
                type: string
                format: uri
        '404':
          description: Dataset not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /datasets/import/:
    post:
      tags:
      - Importing
      summary: Import Dataset
      description: Import a dataset from the local catalog
      operationId: import_dataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetImportForm'
        required: true
      responses:
        '201':
          description: Successful Response
          headers:
            Location:
              description: The URL of the newly created resource
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    DataService:
      properties:
        endpointUrl:
          type: string
          title: Endpointurl
      type: object
      required:
      - endpointUrl
      title: DataService
    Dataset:
      properties:
        identifier:
          type: string
          title: Identifier
        title:
          type: string
          title: Title
        isLocal:
          type: boolean
          title: Islocal
        isShared:
          type: boolean
          title: Isshared
        issued:
          type: string
          format: date
          title: Issued
        theme:
          items:
            type: string
          type: array
          title: Theme
        creator:
          $ref: '#/components/schemas/Person'
        distribution:
          items:
            $ref: '#/components/schemas/Distribution'
          type: array
          title: Distribution
      type: object
      required:
      - identifier
      - title
      - isLocal
      - isShared
      - issued
      - theme
      - creator
      - distribution
      title: Dataset
    DatasetForm:
      properties:
        title:
          type: string
          title: Title
        theme:
          items:
            type: string
          type: array
          title: Theme
        distribution:
          items:
            $ref: '#/components/schemas/Distribution'
          type: array
          title: Distribution
      type: object
      required:
      - title
      - theme
      - distribution
      title: DatasetForm
    DatasetImportForm:
      properties:
        identifier:
          type: string
          title: Identifier
        title:
          type: string
          title: Title
        theme:
          items:
            type: string
          type: array
          title: Theme
        distribution:
          items:
            $ref: '#/components/schemas/Distribution'
          type: array
          title: Distribution
      type: object
      required:
      - identifier
      - title
      - theme
      - distribution
      title: DatasetImportForm
    DatasetShareForm:
      properties:
        marketplaceUrl:
          type: string
          minLength: 1
          format: uri
          title: Marketplaceurl
      type: object
      required:
      - marketplaceUrl
      title: DatasetShareForm
    Distribution:
      properties:
        bytesize:
          anyOf:
          - type: integer
            exclusiveMinimum: 0.0
          - type: 'null'
          title: Bytesize
        mimetype:
          type: string
          title: Mimetype
        checksum:
          type: string
          title: Checksum
        accessService:
          items:
            $ref: '#/components/schemas/DataService'
          type: array
          title: Accessservice
      type: object
      required:
      - bytesize
      - mimetype
      - checksum
      - accessService
      title: Distribution
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthCheck:
      properties:
        status:
          type: string
          title: Status
          examples:
          - OK
      type: object
      required:
      - status
      title: HealthCheck
    OrderDirection:
      type: string
      enum:
      - asc
      - desc
      title: OrderDirection
    PaginatedResult_Dataset_:
      properties:
        page:
          type: integer
          minimum: 1.0
          title: Page
          examples:
          - 1
        size:
          type: integer
          maximum: 100.0
          minimum: 1.0
          title: Size
          examples:
          - 100
        items:
          items:
            $ref: '#/components/schemas/Dataset'
          type: array
          title: Items
      type: object
      required:
      - page
      - size
      - items
      title: PaginatedResult[Dataset]
    Person:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: Person
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
